### ISSUE TITLE
Prevent direct execution of workflow

### ISSUE THREAD

**Issue by jackton1** [tj-actions/coverage-reporter#6]
coverage.py

```yaml
with:
  coverage-py: true
  coverage-args: '...'

```

nyc

```yaml
with:
  nyc: true
  nyc-args: '...'

```
